#ifndef Enum_h__
#define Enum_h__


enum RENDERGROUP { TYPE_PRIORITY, TYPE_NONEALPHA, TYPE_ALPHA, TYPE_UI, TYPE_END };

enum RESOURCETYPE { RESOURCE_STATIC, RESOURCE_LOGIN, RESOURCE_STAGE, RESOURCE_END };


enum Scene_Type {SCENE_LOGIN, SCENE_LOGO, SCENE_STAGE, SCENE_END};


enum MESHNUM { MESHNUM_PLAYER, MESHNUM_GUN, MESHNUM_END };

enum ANIPLAYER { PLAYER_IDLE, PLAYER_ATTACK, PLAYER_MOVE, PLAYER_DIE };

#endif